spring:
  profiles:
    active: dev
jwt:
  # Bearer Token
  tokenHead: 'Bearer '
  # Authorization
  tokenHeader: 'Authorization'
  # Token失效时间 :60*60*24*7
  expiration: 604800
  # 私钥
  secret: '2CF24FE663DBB493E56BA4E31BE6FD03'

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /ums/user/register
      - /ums/user/login
      - /ums/user/info
      - /logout
      - /ums/user/active
      - /minio/upload
      - /bulletin/**
      - /post/list
      - /tip/today
      - /friend/link/**
      - /promotion/all
#      - /activity/all